### PR TITLE
Add azure pipelines to run tests.

### PR DESCRIPTION
**Pull request by ian-hamlin**
**Description:**

I've added some yml files to run the tests in Azure pipelines as it was mentioned in your roadmap.  I appreciate you may not want to use Azure however :) 

Example https://dev.azure.com/morpork73/chit/_build/results?buildId=47

### CODE REVIEW

**Comment by peterheesterman** [comment]
Oh, I love it. 🥇! Thank you.

I am heading to a wedding soon but when i next find some time i am really keen to merge and use this. 
(I will need to do a little reading to figure out how to make it work i expect)

**Comment by peterheesterman** [comment]
I had a look into this quickly just now! Easy as! Thanks so much for the PR!

Just need to figure out how to make it build binaries for me one day. 

Thanks again!

**Comment by ian-hamlin** [comment]
I take a look into building binaries if you want, I did this at the weekend for another project, so it's all still fresh.  There are quite a few examples in some big rust projects, that I ended up cobbling together, but it all seemed to work in the end.

**Comment by peterheesterman** [comment]
Please do. 👍 

Also, I would love to understand it more in depth too so any links to things you found useful in setting it up, send my way if possible.

**Comment by ian-hamlin** [comment]
Mostly I've been browsing some other projects, but the following have also been useful.

This was a good read:
https://nbsoftsolutions.com/blog/azure-pipelines-for-rust-projects

These are some examples that I based my work on:
https://github.com/rustwasm/wasm-bindgen/blob/master/azure-pipelines.yml
https://github.com/tokio-rs/tokio/blob/master/azure-pipelines.yml

Docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops

This is a nice stream where Ryan Levick goes through converting some projects to pipelines.
https://www.youtube.com/watch?v=2RNO99VH1UA&t=970s

I've also started the next phase to do the builds.

**Comment by peterheesterman** [comment]
Epic, has a skim, great resources. Will read more in depth later on. 😁 Thanks for this!

**Pull request merged**
