### PR TITLE
docs(README.md): add a reminder about nix

### LINKED ISSUE #50: List Nix installation instructions in README
As of [today](https://github.com/NixOS/nixpkgs/pull/61428) [Nix](https://nixos.org/nix/) now includes a package for Chit. It will probably take a few days before the package is available on the published channel, but once it is, it would be nice to have Nix installation instructions in the README.

### PR DESCRIPTION
**Pull request by peterheesterman**
**Description:**

Explain how to install `chit` with nix in the readme.

**Related Issues:**

closes #50

### CODE REVIEW

**Comment by lilyball** [comment]
`chit` is now available in the published nixpkgs channel, so with the latest channel, `nix-env -iA nixpkgs.chit` should work.

**Comment by peterheesterman** [comment]
Can confirm, worked for me. 

@lilyball if i want get future versions of chit with nix, what do i need to do to get it updated in the `nixpkgs channel`? Make a PR like you did for this version?

**Comment by lilyball** [comment]
I'm currently watching your repo for releases and will attempt to keep the Nix package up-to-date, but I can't promise anything. If you want to update it yourself, it's relatively straightforward assuming there are no dependency changes:

1. Check out the https://github.com/nixos/nixpkgs repo.
2. Edit the file `pkgs/development/tools/chit/default.nix`
3. Replace the `src.sha256` and `cargoSha256` attribute values with the expression `stdenv.lib.fakeSha256` (this is a convenience that's equivalent to all zeroes)
4. In the root of the `nixpkgs` checkout, run `nix build -f . chit`
5. It will complain about the sha. Copy the new sha it provides and set that as the `src.sha256` attribute value.
6. Run `nix build -f . chit` again
7. It will do some work, then complain about another sha. Copy that new sha and set it as the `cargoSha256` attribute value.
8. Run `nix build -f . chit` one final time. This should succeed.
9. This will produce a `./result` symlink. Test out the `./result/bin/chit` binary to make sure it looks good.
10. Commit this with a title like `chit: 0.1.13 -> 0.1.14`, push this to your fork, create a PR.

If your `chit` update includes changes to dependencies, or adds manpages or shell completion files, the package will need other updates, which you can either learn how to do (mostly by checking out what other packages do for that) or just pinging me if you don't see me already filing a PR for the `chit` update within a few days.

**Comment by lilyball** [comment]
On that note, I see you pushed 0.1.14 an hour ago, so I'll write up a PR now 😉

**Comment by peterheesterman** [comment]
Thank you for the detailed explanation. I will indeed try it some time.

💯Thanks a lot! 💯 

Note to self: make releases count!

**Pull request merged**
